name: generate snake animation

on:
  schedule:
    - cron: '* */8 * * *'
  workflow_dispatch:
  push: { branches: ['master', 'main'] }
jobs:
  build:
    name: Snake Animation Update Data
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: faridhnzz
          svg_out_path: dist/github-contribution-snake.svg

#       - uses: crazy-max/ghaction-github-pages@v2.1.3
#         with:
#           target_branch: output
#           build_dir: dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
